import turtle
turtle.shape("turtle")
turtle.hideturtle()
turtle.penup()
turtle.goto(-150,150)
turtle.pendown()
turtle.speed(2)
turtle.fillcolor("orange")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)

turtle.end_fill()

turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.penup()
turtle.forward(25)
turtle.pendown()
turtle.speed(40)

for i in range(0,24,1):
    turtle.fillcolor("blue")
    turtle.pencolor('blue')
    turtle.begin_fill()
    turtle.circle(100,15)
    turtle.left(165)
    turtle.circle(100,15)
    turtle.left(165)
    turtle.left(15)
    turtle.end_fill()
turtle.pencolor('black')
turtle.speed(2)
turtle.left(180)
turtle.penup()
turtle.forward(25)
turtle.pendown()
turtle.left(90)
turtle.forward(100)

turtle.fillcolor("green")
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

turtle.left(90)
turtle.forward(250)

turtle.penup()
turtle.goto(-100,-50)
turtle.pendown()
s="Mera Bharat Mahan"
for i in s:
    turtle.write(i, font=("times new roman",12))
    turtle.penup()
    turtle.goto(turtle.xcor()+12,turtle.ycor())
    turtle.pendown()

turtle.hideturtle()
